[build]
  command = "cd project && npm install --legacy-peer-deps --force && ./build-cloudflare.sh"
  publish = "project/build"

[build.environment]
  NODE_VERSION = "18.18.0"
  NODE_OPTIONS = "--openssl-legacy-provider"
  SKIP_PREFLIGHT_CHECK = "true"
  GENERATE_SOURCEMAP = "false"
  CI = "true"
